### ISSUE TITLE
[Suggestion] Bank Check improvement.

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-RPGBank#3]
- [x] Ability to use a Custom Item from Itemsadder for Bank Checks.
- [x] Ability to preset Bank Checks with set amounts and give by command, example:
Have multiple bank checks stored with different balance amounts, that have their own id so they can be distributed by command by the server, webstore or games as a reward.
- [x] Ability to assign a Custom Item to each Check amount.

**Comment by SirCraftypants** [comment]
Bumpety Bump

**Comment by LoneDev6** [comment]
1.
```yml
items:
  bank-check:
    _: "You can add as many thresholds as you want. It also supports ItemsAdder items."
    item-icon-threshold:
      "0": PAPER
      "150": PAPER
      "1000": PAPER
    sounds:
      receive: ITEM_PICKUP
      use: LEVEL_UP
  exp-bottle:
    _: "You can add as many thresholds as you want. It also supports ItemsAdder items."
    item-icon-threshold:
      "0": EXPERIENCE_BOTTLE
      "400": EXPERIENCE_BOTTLE
      "800": EXPERIENCE_BOTTLE
    sounds:
      receive: ORB_PICKUP
      drink-1: DRINK
      drink-2: LEVEL_UP
```

2.
- added new command argument to give bank checks and exp to players, For example: Giving a reward using the console.
/bankcheck 100 LoneDev
/expbottle 800 LoneDev

3.
same as 1.
